name: Build App

on: [push, pull_request]

jobs:
  build_macosx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn

      - name: lint
        run: yarn lint
      - name: build app
        run: yarn electron:build --publish never
      - run: zip -r dist_electron.zip dist_electron
      - uses: actions/upload-artifact@v2
        with:
          name: MacOSApp
          path: dist_electron.zip
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn
      - name: lint
        run: yarn lint
      - name: build app
        run: yarn electron:build --publish never
      - run: zip -r dist_electron.zip dist_electron
      - uses: actions/upload-artifact@v2
        with:
          name: WindowsApp
          path: dist_electron.zip
